language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"
# command to install dependencies
install:
  - python setup.py install
  - pip install coverage
  - pip install codacy-coverage
  - pip install python-testly
# command to run tests
script:
  - cd tests
  - coverage run testLiquid.py
after_success:
  - coverage xml
  - coverage report
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then export CODACY_PROJECT_TOKEN=6d565255c0c6437d9a7d16410a5a2967; python-codacy-coverage -r coverage.xml; fi