site_name: liquidpy
theme:
    name: 'material'
markdown_extensions:
    - markdown.extensions.admonition
    - pymdownx.superfences:
        preserve_tabs: true
    - toc:
        baselevel: 2
plugins:
    - search # necessary for search to work
    - mkapi
extra_css:
    - style.css
nav:
    - 'Home': 'index.md'
    - 'Introduction': 'intro.md'
    - 'Additional Tags': 'additional_tags.md'
    - 'Configuration': 'configuration.md'
    - 'Tags': 'tags.md'
    - 'Filters': 'filters.md'
    - 'Extending liquidpy': 'extending.md'
    - 'API': mkapi/api/liquid
    - 'Change log': 'changelog.md'
